name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Build, test, Spotless & SpotBugs
        run: |
          ./gradlew spotlessCheck spotbugsMain build
